# This is a basic workflow to help you get started with Actions

name: mate-terminal

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Pull upstream code
        run: git clone https://github.com/mate-desktop/mate-terminal
        
      - name: init submodules
        run: git submodule init
        working-directory: mate-terminal/
        
      - name: get directory
        run: ls -lah
        working-directory: mate-terminal/
      
      - name: pull git submodules
        run: git submodule update --remote --recursive
        working-directory: mate-terminal/
        
      - name: get directory
        run: ls -lah/
        working-directory: mate-terminal/
