# This is a basic workflow to help you get started with Actions

name: mate-polkit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: installing dependancies
        run: sudo apt install -y dh-make cdbs

      - name: clone upstream code
        run: git clone https://github.com/mate-desktop/mate-polkit
        
      - name: init submodules
        run: git submodule init
        working-directory: mate-polkit/
      
      - name: pull git submodules
        run: git submodule update --remote --recursive
        working-directory: mate-polkit/
      
      - name: make directory
        run: mkdir mate-polkit-debian
        
      - name: clone upstream debain packaging
        run: git clone https://salsa.debian.org/debian-mate-team/mate-polkit
        working-directory: mate-polkit-debian
        
      - name: move debiandirectory
        run: mv mate-polkit-debian/mate-polkit/debian/ mate-polkit/debian/
        
      - name: change to native package
        run: echo "3.0 (native)" > format
        working-directory: mate-polkit/debian/source/
      
      - name: setting version to VERSION-RUN_NUMBER
        run: |
          DATE_STRING=$(date +"%a, %d %b %Y %H:%M:%S %z")
          echo "mate-polkit (1.25.0-$GITHUB_RUN_NUMBER) hirsute; urgency=medium
            *  automated build
            Ubuntu MATE Packaging Bot <guardians@ubuntu-mate.org> $DATE_STRING" >> version
          cat version mate-polkit/debian/changelog > version2
          cat version2 > mate-polkit/debian/changelog
        
      - name: Prepare GPG Signing Key
        run: |
          mkdir -p ~/.gnupg/
          chmod 700 ~/.gnupg
          printf "$BOT_GPG_KEY_BASE64" | base64 --decode > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key
        env:
          BOT_GPG_KEY_BASE64: ${{ secrets.BOT_GPG_KEY_BASE64 }}
        
      - name: build full package for test
        run: dpkg-buildpackage -d -S -sa --sign-key=C77F46B50E6C36E037F9073F6D69B53ED298168C
        working-directory: mate-terminal/
      
      - name: upload to ppa
        run: dput ppa:ubuntu-mate-bot/daily-brew ./*.changes
