# This is a basic workflow to help you get started with Actions

name: mate-terminal

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: installing dependancies
        run: sudo apt install -y dh-make

      - name: clone upstream code
        run: git clone https://github.com/mate-desktop/mate-terminal
        
      - name: init submodules
        run: git submodule init
        working-directory: mate-terminal/
      
      - name: pull git submodules
        run: git submodule update --remote --recursive
        working-directory: mate-terminal/
      
      - name: make directory
        run: mkdir mate-terminal-debian
        
      - name: clone upstream debain packaging
        run: git clone https://salsa.debian.org/debian-mate-team/mate-terminal
        working-directory: mate-terminal-debian
        
      - name: move debiandirectory
        run: mv mate-terminal-debian/mate-terminal/debian/ mate-terminal/debian/
        
      - name: change to native package
        run: echo "3.0 (native)" > format
        working-directory: mate-terminal/debian/source/
      
      - name: setting version to VERSION-RUN_NUMBER
        run: |
          DATE_STRING=$(date +"%a, %d %b %Y %H:%M:%S %z")
          echo "mate-terminal (1.25.0-$GITHUB_RUN_NUMBER) hirsute; urgency=medium
            *  automated build
            Ubuntu MATE Packaging Bot <guardians@ubuntu-mate.org> $DATE_STRING" >> version
          cat version mate-terminal/debian/changelog > version2
          cat version2 > mate-terminal/debian/changelog
        
      - name: build full package for test
        run: dpkg-buildpackage -d -S -sa -uc -us
        working-directory: mate-terminal/
      
      - name: get directory
        run: ls -lah
